### ISSUE TITLE
Periodically tagging new releases

### ISSUE THREAD

**Issue by codygibb** [golang/mock#141]
Thanks for all the hard work on this package, it's great to see new functionality being added! However, for consumers who rely on semver compatible releases, it's difficult to include new commits as we're forced to pin our dependency to the commit sha, rather than a major version. Would you consider tagging each commit with a version, or just periodically tagging minor releases?

**Comment by simonkinsella-bbc** [comment]
I agree that this would be desirable.  A recent breaking change prevents us from using the latest version of gomock, and due to the size of our app and scale of the breakage we will not be in a position to modify our application. Therefore tagging releases, esp if introducing breaking changes in compatibility, would be helpful. Thanks.

**Comment by balshetzer** [comment]
Will do.
