### ISSUE TITLE
Error Message Arg Order Flipped

### ISSUE THREAD

**Issue by RONNCC** [golang/mock#150]
It seems like the order of args is switched in https://github.com/golang/mock/blob/b3e60bcdc577185fce3cf625fc96b62857ce5574/gomock/call.go#L322

```
		if len(c.args) != c.methodType.NumIn() && len(args) != len(c.args) {
			return fmt.Errorf("Expected call at %s has the wrong number of arguments. Got: %d, want: %d",
				c.origin, len(args), len(c.args))
		}
```
I get
`Expected call at /Users/rghose/go/src/git.soma/.../pkg_test.go:230 has the wrong number of arguments. Got: 3, want: 5` when I call it with 5 arguments and it only takes 3; 

e.g.
`mockLogger.EXPECT().Error(gomock.Any(), gomock.Any(), gomock.Any(),gomock.Any(),gomock.Any())`

**Comment by balshetzer** [comment]
I _think_ this is correct. 

We have an **expected** call created with mockLogger.EXPECT().Error(any, any, any, any, any).
Then we have an **actual** call somewhere in the code where Error is getting 3 arguments. 

Gomock is saying that the actual call didn't match this expected call because it has the wrong number of arguments. The actual call would need 5 arguments to match the expected call (want 5) but it only has 3 (got 3).

It's confusing but I think it's right. Correct me if I'm wrong.

**Comment by RONNCC** [comment]
Seems like it maybe the wording should be changed since the expected call should be assumed correct rather than incorrect - that would seem to contradict the idea of TDD no?

**Comment by balshetzer** [comment]
I think that's exactly what it's saying: The expected call has 5 arguments, yes? And the actual call has 3? So this is saying the 5 is correct and we want 5 but got 3.
