### ISSUE TITLE
panic on call method without any match mocker  

### ISSUE THREAD

**Issue by sword2ya** [golang/mock#155]
these is some information:

time="2018-03-03T12:27:25+08:00" level=info msg="ready start server" lisAddr="0.0.0.0:16566"
panic: test executed panic(nil) or runtime.Goexit

goroutine 8 [running]:
testing.tRunner.func1(0xc4201622d0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:366 +0x147
testing.(*common).FailNow(0xc4201620f0)
	/usr/local/go/src/testing/testing.go:544 +0x39
testing.(*common).Fatalf(0xc4201620f0, 0x969380, 0x24, 0xc420166660, 0x3, 0x3)
	/usr/local/go/src/testing/testing.go:588 +0x83
rsctl/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc42014e540, 0x8bcf40, 0xc420047350, 0x95b6e8, 0xb, 0xc420047800, 0x1, 0x1, 0x0, 0x0, ...)
	/home/anjiawei/go/src/rsctl/vendor/github.com/golang/mock/gomock/controller.go:130 +0x5dc

**Comment by balshetzer** [comment]
Hi,

I don't think this is a bug in gomock. The test failed because of an unrecognized call to the mock. Gomock called t.Fatalf and that function called runtime.Goexit.

The most likely reason for this is that you used t.Run to run a nested test but created the mock controller outside t.Run so the wrong t (or the wrong instance of testing.T) is passed to gomock. Here is a better explanation: https://github.com/golang/mock/issues/51#issuecomment-324423178

I hope this helps.
