### ISSUE TITLE
Can't use mocks when recieved input has random fields.

### ISSUE THREAD

**Issue by noibar** [golang/mock#43]
you can't use EXPECT() for functions that recieve a complex object with random values. Other then that, objects that hold fields that are irellevant for the matching can't be matched with the given matchers. (I hope you don't mind the exessive tautology :))

In order to solve this, an additional matcher can be implemented. I thought to implement a StrMatcher, that will match between the objects String(). This way, if you want to ignore some of the fields in the matching process, you can implement a String() function that returns a description of all the object's interesing fields.

**Comment by euank** [comment]
Additional matchers don't have to be part of the gomock project.

If you implement the `StrMatcher` struct in your own code and ensure it conforms to the `gomock.Matcher` interface, then [this code](https://github.com/golang/mock/blob/bd3c8e81be01eef76d4b503f5e687d2d1354d2d9/gomock/controller.go#L87) will notice that it conforms to said interface and use it.

For example, I once wanted to just match a small number of known fields of an http request, since the request  (just method and url) since those resulted in a more readable test (and the `Date` field is effectively random). I wrote [this matcher](https://github.com/aws/amazon-ecs-agent/blob/304495bc6defdcc98f15a97b271c41127dba5e48/agent/httpclient/mock/gomock_helpers.go#L27) and used it like [this](https://github.com/aws/amazon-ecs-agent/blob/d5e8c51cf0199e1766ac819e8d3bef058a916426/agent/acs/update_handler/updater_test.go#L122).

**Comment by awe76** [comment]
May I suggest a slight but very useful extension of the matchers API like:

```
type doMatch[T any] struct {
	match func(v T) bool
	v     T
}

func DoMatch[T any](m func(v T) bool) gomock.Matcher {
	return &doMatch[T]{
		match: m,
	}
}

func (o *doMatch[T]) Matches(x interface{}) bool {
	v, ok := x.(T)
	if !ok {
		return false
	}

	o.v = v
	return o.match(o.v)
}

func (o *doMatch[T]) String() string {
	return fmt.Sprintf("is matched to %v", o.v)
}
```

utilization:

```
Expect().Foo(
    gomock.Any(DoMatch(func(v Bar) bool {
            return v.Name == 'Billy'
    }),
))
```
