### ISSUE TITLE
New `mockgen` option to allow users to add build tag on mock file

### ISSUE THREAD

**Issue by sanposhiho** [golang/mock#636]
*Requested feature* 

New option to allow users to add build tag on mock file

*Why the feature is needed* 

In many cases, mocks should be used only in test. And we often use the build tag to avoid mistakenly importing test code from normal(non-test) files.
It would be great if we could add a build tag on a mock file to prevent mocks from being imported from other normal files.
(Or is there already a way for this?)

**Comment by codyoss** [comment]
Instead of using a build tag I think a better solution is just to generate mocks for package `foo` in package `foo_test`. This is a pretty common pattern for users. WDYT?

**Comment by sanposhiho** [comment]
Given that not all tests can be written in `XXX_test` packages, giving a build tag seems more reasonable than recommending generating mocks in package `XXX_test`.

**Comment by yidane** [comment]
But it can not be used in another package if the mocks named XXX_test

**Comment by codyoss** [comment]
The package could also be `foo`. The import bit is that the mocks are in a test file: `*_test.go`. Another option if you really wanted to do something like this would be to use the header flag and have this as a part of your header. Closing this issue since there are workaround for this and we like to error on the side of not adding new flags if necessary.
